insert into students (teachers_id, classes_id, first_name, last_name) values (1, 1, 'Deb', 'Pillington');
insert into students ( teachers_id, classes_id, first_name, last_name) values (1, 1, 'Biron', 'Doge');
insert into students ( teachers_id, classes_id, first_name, last_name) values (1, 1, 'Maggi', 'Carter');
insert into students ( teachers_id, classes_id, first_name, last_name) values (1, 1, 'Shirlene', 'Jeynes');
insert into students ( teachers_id, classes_id, first_name, last_name) values (1, 1, 'Doloritas', 'Fass');
insert into students ( teachers_id, classes_id, first_name, last_name) values (1, 1, 'Grenville', 'Burgill');
insert into students ( teachers_id, classes_id, first_name, last_name) values (1, 1, 'Kile', 'Billison');
insert into students ( teachers_id, classes_id, first_name, last_name) values (1, 1, 'Giusto', 'Calfe');
insert into students ( teachers_id, classes_id, first_name, last_name) values (1, 1, 'Gabi', 'Sutor');
insert into students ( teachers_id, classes_id, first_name, last_name) values (1, 1, 'Etan', 'Dudderidge');
insert into students ( teachers_id, classes_id, first_name, last_name) values (1, 1, 'Arlana', 'Shetliff');
insert into students ( teachers_id, classes_id, first_name, last_name) values (1, 1, 'Harland', 'Creffield');
insert into students ( teachers_id, classes_id, first_name, last_name) values (1, 1, 'Perri', 'Dullaghan');
insert into students ( teachers_id, classes_id, first_name, last_name) values (1, 1, 'Jedediah', 'Galland');
insert into students ( teachers_id, classes_id, first_name, last_name) values (1, 1, 'Chance', 'Lawler');
insert into students ( teachers_id, classes_id, first_name, last_name) values (1, 2, 'August', 'Aird');
insert into students ( teachers_id, classes_id, first_name, last_name) values (1, 2, 'Hercules', 'Langtree');
insert into students ( teachers_id, classes_id, first_name, last_name) values (1, 2, 'Lurlene', 'Sweatman');
insert into students ( teachers_id, classes_id, first_name, last_name) values (1, 2, 'Randie', 'Feltham');
insert into students ( teachers_id, classes_id, first_name, last_name) values (1, 2, 'Alfons', 'Turley');
insert into students ( teachers_id, classes_id, first_name, last_name) values (1, 2, 'Margot', 'Pepi');
insert into students ( teachers_id, classes_id, first_name, last_name) values (1, 2, 'Fritz', 'Goodsal');
insert into students ( teachers_id, classes_id, first_name, last_name) values (1,2 , 'Brocky', 'Gumary');
insert into students ( teachers_id, classes_id, first_name, last_name) values (1, 2, 'Rosa', 'Beswetherick');
insert into students ( teachers_id, classes_id, first_name, last_name) values (1, 2 , 'Tara', 'Clewer');
insert into students ( teachers_id, classes_id, first_name, last_name) values (1, 2, 'Nehemiah', 'Mathonnet');
insert into students ( teachers_id, classes_id, first_name, last_name) values (1, 2, 'Maurine', 'Ferrulli');
insert into students ( teachers_id, classes_id, first_name, last_name) values (1, 2, 'Art', 'Castanares');

